# Generated by Django 5.0.3 on 2024-04-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_users_age_alter_users_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='billing_address',
            field=models.TextField(null=True),
        ),
    ]
