# Generated by Django 5.0.3 on 2024-05-25 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orders_shipping_rate_alter_orders_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
